objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <fields>
        <fullName>copado__URI__c</fullName>
        <description>HTTPS or SSH URL to connect to the Git Repository.</description>
        <inlineHelpText>HTTPS or SSH URL to connect to the Git Repository.</inlineHelpText>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QCloudsSaaS__Instance__c.object
<CustomObject>
    <description>added from sfdx plugin</description>
    <fields>
        <fullName>QCloudsSaaS__Description__c</fullName>
        <description>Org description - Set on the Quality Clouds scan site when the instance was registered</description>
        <inlineHelpText>Org description - Set on the Quality Clouds scan site when the instance was registered</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QCloudsSaaS__Environment_Type__c</fullName>
        <description>Org environment type - Set on the Quality Clouds scan site when the instance was registered</description>
        <inlineHelpText>Org environment type - Set on the Quality Clouds scan site when the instance was registered</inlineHelpText>
        <label>Environment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QCloudsSaaS__ID__c</fullName>
        <description>Instance id from QualityClouds</description>
        <externalId>true</externalId>
        <inlineHelpText>Instance id from QualityClouds</inlineHelpText>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>QCloudsSaaS__Instance_Type__c</fullName>
        <description>SaaS Platform type</description>
        <inlineHelpText>SaaS Platform type</inlineHelpText>
        <label>Instance Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QCloudsSaaS__Is_Featured_Banch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Featured Banch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QCloudsSaaS__url__c</fullName>
        <description>Org URL - Detected automatically during scan. Not available for feature branch scans</description>
        <inlineHelpText>Org URL - Detected automatically during scan. Not available for feature branch scans</inlineHelpText>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Run_QualityClouds_Scan_Page_Controller.cls
public with sharing class Run_QualityClouds_Scan_Page_Controller {
    public final SObject parent{get;set;}
    public String projectId ;
    public String pipeId ;
    public String repoID ;
    public String repoURL{get;set;}

    public String message{get;set;}

    public QCloudsSaaS__Instance__c instance;

    public Run_QualityClouds_Scan_Page_Controller(ApexPages.StandardController controller) {

        parent = controller.getRecord();

    }

    public void doScan(){
        projectId = [SELECT copado__Project__c FROM copado__User_Story__c WHERE Id = :parent.id].copado__Project__c;

        pipeId = [SELECT copado__Deployment_Flow__c FROM copado__Project__c WHERE Id = :projectId].copado__Deployment_Flow__c;

        repoID = [SELECT copado__Git_Repository__c FROM copado__Deployment_Flow__c WHERE Id = :pipeId].copado__Git_Repository__c;

        repoURL = [SELECT copado__URI__c FROM copado__Git_Repository__c WHERE Id = :repoID].copado__URI__c;

        repoURL = '%' + repoURL.replace('https://github.com/','').replace('git@github.com:','');

        instance = [SELECT QCloudsSaaS__url__c, QCloudsSaaS__Description__c, QCloudsSaaS__ID__c, QCloudsSaaS__Environment_Type__c, QCloudsSaaS__Instance_Type__c, QCloudsSaaS__Is_Featured_Banch__c, Id FROM QCloudsSaaS__Instance__c WHERE QCloudsSaaS__url__c LIKE :repoURL ORDER BY CreatedDate DESC LIMIT 1];

        if(instance != null){
            QCloudsSaaS.globalCallsToQC globalCallsToQCObj = new QCloudsSaaS.globalCallsToQC();
            if(!Test.isRunningTest()) boolean succsess = globalCallsToQCObj.execute_scann(instance, 'feature/' + [SELECT Name FROM copado__User_Story__c WHERE Id = :parent.id].Name);
            message = 'Quality Clouds scan successfully launched';
        } else {
            message = 'No matching Quality Clouds instance was found for this Copado Repository. Please make sure that the Quality Clouds instances have been imported';
        }
    }

}